# -*- coding: utf-8 -*-
"""Fine Tuning VGG16 Keras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AY238bipo4l-XvcNwv5FP164-yF8hAhV
"""

import tensorflow as tf
from tensorflow import keras

vgg = keras.applications.vgg16.VGG16()

vgg.summary()

model = keras.Sequential()
for layer in vgg.layers:
  model.add(layer)

model.summary()

model.layers.pop()

model.summary()

for layer in model.layers:
  layer.trainable = False

model.summary()

model.add(keras.layers.Dense(2, activation='softmax'))

model.summary()

model.compile(optimizer='adam(lr = 0.0001)', loss = 'categorical_crossentropy', metrics=['accuracy'])

model.fit()